name: weread sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libsqlite3-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: memos sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          MEMOS_TOKEN: ${{ secrets.MEMOS_TOKEN }}
        run: |
          python3 ./main.py sync_memos "${{secrets.NOTION_TOKEN}}" "${{secrets.DATABASE_ID}}" "${{secrets.MEMOS_TOKEN}}"
